#!/bin/sh
#
# Usage: dev <project>
# Description: Opens the specified project in VSCode
function dev() {
    case $1 in
        dotfiles)       code ~/.dotfiles                        ;;
        proxy)          code ~/projects/proxy                   ;;
        ushell)         code ~/projects/ushell                  ;;
        pagecomposer)   code ~/projects/tbd                     ;;
        spacedesigner)  code ~/projects/tbd                     ;;
        ui5)            code ~/project/openui5                  ;;
        e2e)            code ~/projects/contentManager/e2etests ;;
        wfs)            code ~/projects/workflow-service        ;;
        claudemd)       code ~/.claude/CLAUDE.md                ;;
        *)              echo "Unknown project: $1"              ;;
    esac
}
