alias ls="ls -F -A"
alias ll="ls -lAh"
alias l="ls -lh"
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias o="open ."
alias spacer="defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type='spacer-tile';}' && killall Dock"
alias intellij="open -a \"IntelliJ IDEA\" ."
alias ij="open -a \"IntelliJ IDEA\" ."
alias mt="mvn test"
alias mc="mvn compile"
alias mi="mvn install"
alias mcc="mvn clean compile"
alias mci="mvn clean install"
alias mcv="mvn clean verify"
alias mc="mvn clean"
alias mct="mvn clean test"